
application.externalized-configuration-test-cover: 15-Application properties packaged inside your jar (application.properties and YAML variants).
application.externalized-configuration-15-application.properties-YAML: 15-Application properties packaged inside your jar (application.properties and YAML variants).

