spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:schema-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test

logging:
  level:
    com:
      github:
        flysium:
          io:
            springboot:
              repository: DEBUG

# server
server:
  port: 9090

mybatis:
  type-aliases-package: com.github.flysium.io.springboot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 控制二级缓存的总开关, 默认 true, 如果启用 Executor 会被代理为 CachingExecutor
    # see org.apache.ibatis.session.Configuration#newExecutor
    cache-enabled: true

