spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:schema-h2.sql
    url: jdbc:h2:mem:test
    username: sa
    password: sa

logging:
  level:
    com:
      github:
        flysium:
          io:
            springboot:
              repository: DEBUG

# server
server:
  port: 9090

mybatis:
  type-aliases-package: xyz.flysium.dao.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # Mybatis仅支持association关联对象和collection关联集合对象的延迟加载，association指的就是一对一，collection指的就是一对多查询。
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    # 控制二级缓存的总开关, 默认 true, 如果启用 Executor 会被代理为 CachingExecutor
    # see org.apache.ibatis.session.Configuration#newExecutor
    cache-enabled: true

