spring:
  application:
    name: spring-boot2-cxf

# server
server:
  port: 8293

# cxf
cxf:
  # 默认为 /services 路径
  path: /services
  jaxrs:
    client:
      address: http://localhost:8293/services/helloservice
      headers.accept: text/plain
      classes-scan-packages: xyz.flysium.api