
externalized-configuration-test-cover: 13-Profile-specific application properties packaged inside your jar (application-{profile}.properties and YAML variants).
externalized-configuration-13-application-{profile}.properties-YAML: 13-Profile-specific application properties packaged inside your jar (application-{profile}.properties and YAML variants).

