spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:schema-h2.sql
    data: classpath:data-h2.sql

logging:
  level:
    xyz.flysium.dao: DEBUG

# server
server:
  port: 9091

