spring:
  application:
    name: spring-boot2-actuator
  # jmx
  jmx:
    enabled: true
# actuator management
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# server
server:
  port: 8001
