externalized-configuration-test-cover: 16-@PropertySource annotations on your @Configuration classes.
externalized-configuration-16-Configuration-PropertySource: 16-@PropertySource annotations on your @Configuration classes.