spring:
  application:
    name: spring-boot2-async

# server
server:
  port: 8008

# executor
executor:
  # 线程名称前缀
  thread-name-prefix: app-
  # 核心线程池大小
  core-pool-size: 20
  # 最大线程池大小
  max-pool-size: 50
  # 线程池中超过corePoolSize数目的空闲线程最大存活时间，单位为秒
  keep-alive-seconds: 60
  # 阻塞队列大小
  queue-capacity: 2000

