spring:
  profiles:
    active: jdbc
  application:
    name: spring-boot2-sql-database-jdbc-jndi

# server
server:
  port: 8312

logging:
  level:
    org:
      hibernate: DEBUG

---
spring:
  profiles: jndi

  datasource:
    jndi-name: java:comp/env/jdbc/myDataSource # java:jboss/datasources/myDataSource

---
spring:
  profiles: jdbc

  datasource:
    ## 数据库连接设置
    url: jdbc:mysql://localhost:3306/test
    username: root  #配置数据库用户名
    password: root123  #配置数据库密码
    driverClassName: com.mysql.jdbc.Driver


